spring.application.name=backend
# H2 Database Connection Settings
spring.datasource.url=jdbc:h2:mem:ecomdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin123

# Hibernate (JPA) Settings: Yeh Spring ko batata hai ki tables khud bana do
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Web Console: Taki hum browser mein apna database dekh sakein
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console