spring.application.name=backend

# 1. H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 2. Database Connection Settings
spring.datasource.url=jdbc:h2:mem:ecomdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin123

# 3. JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true